AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Check with yard instead.
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true
